# Generated by Django 5.2.14 on 2026-05-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('recovery_type', models.CharField(max_length=100)),
                ('wallet_type', models.CharField(max_length=100)),
                ('wallet_amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='title',
        ),
    ]
