# Generated by Django 5.2.14 on 2026-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otzyvy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='reviews/')),
            ],
        ),
    ]
