# Generated by Django 5.2.14 on 2026-05-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_otzyvy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Zaiavka',
        ),
    ]
